name: Build Flutter desktop

on:
  # lo lanzas a mano o lo puedes ampliar con push/pull_request si quieres
  workflow_dispatch:

jobs:
  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # 1. Clona el repo
      - uses: actions/checkout@v4

      # 2. Lee la versión de .flutter-version y la exporta para los demás pasos
      - name: Read .flutter-version
        id: get-version
        run: |
          ver=$(cat .flutter-version)
          echo "FLUTTER_VERSION=$ver" >> "$GITHUB_ENV"

      # 3. Instala Flutter con la versión detectada
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      # 4. Dependencias
      - name: Pub get
        run: flutter pub get

      # 5. Build según SO
      - name: Build desktop binary
        shell: bash         # obliga a bash en Windows para el if [[ … ]]
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            flutter build linux --release
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            flutter build windows --release
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            flutter build macos --release
          fi

      # 6. Empaquetar artefacto
      # 6-a Linux → ZIP
      - name: Zip artifact (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          cd build/linux
          zip -r ../../linux-desktop.zip .

      # 6-b Windows → ZIP vía PowerShell
      - name: Zip artifact (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: |
          Compress-Archive -Path 'build/windows/runner/Release/*' -DestinationPath windows-desktop.zip

      # 6-c macOS → DMG simple
      - name: Create DMG (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          mkdir -p dist
          hdiutil create -volname YourApp \
            -srcfolder "build/macos/Build/Products/Release" \
            -ov -format UDZO dist/macos-desktop.dmg

      # 7. Subida de artefactos
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-desktop
          path: |
            linux-desktop.zip
            windows-desktop.zip
            dist/macos-desktop.dmg
            build/**/Release/**        # sube binarios sueltos por si falló el empaquetado
          if-no-files-found: error
